version: '3.4'

services:
  admin:
    image: ${DOCKER_REGISTRY-}admin
    build:
      context: .
      dockerfile: Admin/Dockerfile
    ports:
    - 45701:443

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: APIGateWay/Dockerfile
    ports:
    - 45700:443

